version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1 
    volumes:
      - .:/code
      - ./sqlite:/sqlite
