version: '3'

services:
  wgetbash:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    restart: always
    container_name: "wgetbash"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1
    volumes:
      - .:/code
      - ./sqlite:/sqlite
