# Generated by Django 5.0.1 on 2024-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_script_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='url',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
