# Generated by Django 5.0.1 on 2024-02-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_template_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='color',
            field=models.IntegerField(choices=[(0, 'D96661'), (1, 'BF96C3'), (3, '6EBCB4'), (4, 'D9D9D9')], default=0),
        ),
    ]
