### install REST client plugin

POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "serega", "password": "1234"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "", "password": "fwfew", "email": "wdaawd@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token b0e51f5534ba19dcd5dafb63dedf0f26b1aadcf3

{}

###

GET http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token 67d00197d68d8465278c3be07636ff813dd5bbc2

{}

###

