### install REST client plugin

POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "serega", "password": "1234"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "", "password": "fwfew", "email": "wdaawd@gmail.com"}

###

GET http://127.0.0.1:80/tg_logout
Content-Type: application/json
Authorization: Token f11c5f4d47922a3415ce98ac0c9017a1ac0862bc

{}

###

GET http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token 67d00197d68d8465278c3be07636ff813dd5bbc2

{}

###

POST https://api.telegram.org/bot6765553972:AAGaoqoMWZ93C5wGHWe8gzmC-sIuYG6-F-Y/setWebhook
Content-Type: application/json

{"url": "https://0875-178-66-157-152.ngrok-free.app/bot/"}