# Generated by Django 5.0.2 on 2024-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=256)),
                ('message_id', models.CharField(max_length=256)),
                ('username', models.CharField(default=None, max_length=256, null=True)),
                ('first_name', models.CharField(default=None, max_length=256, null=True)),
                ('last_name', models.CharField(default=None, max_length=256, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('callback', models.CharField(default=None, max_length=256, null=True)),
                ('video', models.CharField(default=None, max_length=256, null=True)),
                ('audio', models.CharField(default=None, max_length=256, null=True)),
                ('voice', models.CharField(default=None, max_length=256, null=True)),
                ('video_note', models.CharField(default=None, max_length=256, null=True)),
                ('document', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
    ]
