# Generated by Django 5.0.1 on 2024-01-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrong_password_count',
            field=models.IntegerField(default=0),
        ),
    ]
