# Generated by Django 5.0.1 on 2024-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_profile_avarar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='selected_option',
            new_name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.IntegerField(choices=[(0, 'D96661'), (1, 'BF96C3'), (3, '6EBCB4'), (4, 'D9D9D9')], default=0),
        ),
    ]
