# Generated by Django 5.0.1 on 2024-02-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default='anonym user', max_length=20),
        ),
    ]
